import {
  ArrowLeft,
  ArrowRight,
  AtSign,
  BadgeCheck,
  Briefcase,
  Calendar,
  CalendarDays,
  CalendarX2,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheckBig,
  Clock3,
  Contact,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Globe,
  GraduationCap,
  History,
  House,
  IdCard,
  Info,
  KeyRound,
  Link2,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  MailOpen,
  Menu,
  MapPin,
  Mars,
  MousePointerClick,
  Network,
  Newspaper,
  Pencil,
  Phone,
  PlayCircle,
  Rocket,
  RotateCcw,
  Save,
  Share2,
  Shield,
  Sparkles,
  Terminal,
  ToggleRight,
  User,
  Users,
  UsersRound,
  Venus,
  ChevronLeft,
  Search,
  Trash2,
  Inbox,
  X,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

const ICON_MAP: Record<string, LucideIcon> = {
  ads_click: MousePointerClick,
  alternate_email: AtSign,
  account_tree: Network,
  article: FileText,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  badge: IdCard,
  calendar_month: CalendarDays,
  calendar_today: CalendarDays,
  call: Phone,
  check: Check,
  check_circle: CircleCheckBig,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  contacts: Contact,
  east: ArrowRight,
  edit: Pencil,
  error: CircleAlert,
  event: Calendar,
  event_busy: CalendarX2,
  expand_more: ChevronDown,
  female: Venus,
  flag: BadgeCheck,
  group_off: Users,
  groups: Users,
  history: History,
  history_edu: History,
  home: House,
  hub: Network,
  inbox: Inbox,
  info: Info,
  language: Globe,
  link: Link2,
  location_on: MapPin,
  lock: Lock,
  lock_clock: Clock3,
  lock_reset: KeyRound,
  logout: LogOut,
  mail: Mail,
  menu: Menu,
  man: User,
  male: Mars,
  mark_email_unread: MailOpen,
  newspaper: Newspaper,
  open_in_new: ExternalLink,
  person: User,
  photo_camera: Camera,
  play_circle: PlayCircle,
  progress_activity: LoaderCircle,
  restart_alt: RotateCcw,
  rocket_launch: Rocket,
  save: Save,
  school: GraduationCap,
  search: Search,
  security: Shield,
  send: ArrowRight,
  share: Share2,
  task_alt: CircleCheckBig,
  terminal: Terminal,
  toggle_on: ToggleRight,
  delete: Trash2,
  verified: BadgeCheck,
  visibility: Eye,
  visibility_off: EyeOff,
  vpn_key: KeyRound,
  woman: User,
  work: Briefcase,
  workspace_premium: BadgeCheck,
  diversity_1: UsersRound,
  diversity_3: UsersRound,
  auto_awesome: Sparkles,
};

type MaterialIconProps = {
  name: string;
  className?: string;
};

export function MaterialIcon({ name, className }: MaterialIconProps) {
  const Icon = ICON_MAP[name] ?? Circle;
  return <Icon className={cn("inline-block align-middle", className)} />;
}

